<!DOCTYPE html>
<html>

<head>
    <title>About</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>

    <nav>
        <a href="index.html">Home</a>
        <a href="details.html">Details</a>
        <a href="about.html">About</a>
        <a href="new-character-form.html">Add a Character</a>
    </nav>

    <div class="about">
        <h1>About This Website</h1>

        <img src="goku.jpeg" alt="Goku">

        <p>
            I chose dragon ball because it was a show that I grew up with and it continued to be a show that I watched
            as I got older.
            I wanted to showcase this show and the impact it has had on my life.

        </p>

    </div>

    <a href="index.html" class="back-button">Back to Gallery</a>

</body>

</html>